name: Jira Issue Updater

on: [pull_request]

jobs:
  update-jira-issue:
    name: Update Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: frieder/gha-jira-login@v1
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_DOMAIN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Update Fields
        id: updatefields
        uses: frieder/jira-issue-updater@v1
        with:
          issue: SCRUM-1
          labels: + bar

      # this action will only be reached when failOnError was set to false in the previous step
      - name: Print Outputs
        run: |
          echo "REPO_NAME: ${{ github.event.repository.name }}"
          echo "HAS ERRORS: ${{ steps.updatefields.outputs.hasErrors }}"
          echo "IDs SUCCESS: ${{ steps.updatefields.outputs.successful }}"
          echo "IDs ERROR: ${{ steps.updatefields.outputs.failed }}"




#name: action-jira-linter
#on: [pull_request]
#
#jobs:
#  action-jira-linter:
#    runs-on: ubuntu-latest
#    steps:
#      - name: determine associated issue id
#        id: get-jira
#        run: |
#          title="${{github.event.pull_request.title}}"
#          echo "1 title=$title"
#          echo "1 ====================="
#          ticket_id="SCRUM-1"
#          echo "2 ticket-id=$ticket_id"
#          echo "2 ====================="
#          if echo $ticket_id | grep -Eqx '[A-Z]+-[0-9]+'; then
#            echo "7 ticket-id=$ticket_id"
#            echo "ticket-id=$ticket_id" >> $GITHUB_OUTPUT
#          fi
#          echo "3 ====================="
#
#      - uses: insidewhy/action-get-jira-issue@v1
#        id: jira
#        with:
#          user: ${{ secrets.JIRA_USER }}
#          token: ${{ secrets.JIRA_TOKEN }}
#          base-url: ${{ secrets.JIRA_DOMAIN }}
#          ticket-id: ${{ steps.get-jira.outputs.ticket-id }}
#
#      - name: echo jira details
#        run:
#          echo "4 running jira details"
#          echo ${{ steps.jira.outputs.link }} - ${{ steps.jira.outputs.labels[1] }} - ${{ steps.jira.outputs.summary }} -


#      - uses: btwrk/action-jira-linter@v1.0.1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          jira-token: ${{ secrets.JIRA_TOKEN }}
#          jira-base-url: ${{ secrets.JIRA_DOMAIN }}
#          jira-user: ${{ secrets.JIRA_USER }}
#
