name: action-jira-linter
on: [pull_request]

jobs:
  action-jira-linter:
    runs-on: ubuntu-latest
    steps:
      - name: determine associated issue id
        id: get-jira
        run: |
          title="${{github.event.pull_request.title}}"
          echo "1 title=$title"
          echo "=====================" 
          ticket_id="https://kieranheg.atlassian.net/browse/SCRUM-1"
          if echo $ticket_id | grep -Eqx '[A-Z]+-[0-9]+'; then
            echo "ticket-id=$ticket_id"
          fi
          echo "ticket-id=$ticket_id"

      - uses: insidewhy/action-get-jira-issue@v1
        id: jira
        with:
          user: ${{ secrets.JIRA_USER }}
          token: ${{ secrets.JIRA_TOKEN }}
          base-url: ${{ secrets.JIRA_DOMAIN }}
          ticket-id: ${{ steps.get-jira.outputs.ticket-id }}

      - name: echo jira details
        run: echo ${{ steps.jira.outputs.link }} - ${{steps.jira.outputs.summary}}


#      - uses: btwrk/action-jira-linter@v1.0.1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          jira-token: ${{ secrets.JIRA_TOKEN }}
#          jira-base-url: ${{ secrets.JIRA_DOMAIN }}
#          jira-user: ${{ secrets.JIRA_USER }}
#
