name: action-jira-linter
on:
  pull_request:
    branches:
      - main
jobs:
  action-jira-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: btwrk/action-jira-linter@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_DOMAIN }}
          jira-user: ${{ secrets.JIRA_USER }}
